[package]
name = "kapun-dcql-rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib", "lib"]
name = "kapun_dcql_rust"

[dependencies]
uniffi.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
jlc = { git = "https://github.com/UbiqueInnovation/possum.git", optional = true }
kapun-util-rust = { path = "../../kapun-util/rust" }
kapun-credentials-rust = { path = "../../kapun-credentials/rust", default-features = false }

[features]
default = ["uniffi"]
bbs = ["kapun-credentials-rust/bbs"]
mdoc = ["kapun-credentials-rust/mdoc"]
sdjwt = ["kapun-credentials-rust/sdjwt"]
w3c = ["kapun-credentials-rust/w3c"]
openbadges = ["kapun-credentials-rust/openbadges"]
uniffi = ["kapun-credentials-rust/uniffi"]
builtin_parsers = ["bbs", "mdoc", "sdjwt", "w3c", "openbadges"]
jlc = ["dep:jlc"]
