generate_serializable_records = true
generate_immutable_records = true
import_pointer_from = ["uniffi.kapun_credential_core_rust", "uniffi.kapun_util_rust"]
skip_serializer_for = [
    "DcqlMatchResponse",
    "Credential", "CredentialOptions", "Disclosure", "CredentialSetOption", "SetOption"]
