[package]
name = "kapun-pdf-rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib", "lib"]
name = "kapun_pdf_rust"

[dependencies]
uniffi.workspace = true
typst = { git = "https://github.com/typst/typst.git", tag = "v0.14.2", package = "typst" }
typst-assets = {version = "0.14.0", features = ["fonts"]}
typst-pdf = { git = "https://github.com/typst/typst.git", tag = "v0.14.2", package = "typst-pdf" }
typst-render = { git = "https://github.com/typst/typst.git", tag = "v0.14.2", package = "typst-render", optional = true }
ureq.workspace = true
fontdb = "0.16.2"
# Fetching and unzipping packages
zune-inflate = { version = "0.2", default-features = false, features = [
    "gzip",
    "std",
] }
# utils
time = "0.3"
ttf-parser = "0.25.1"
tar = "0.4"

[features]
default = ["uniffi"]
uniffi = []
png = ["dep:typst-render"]
